# 2024.12.08

cc_library (
  name="core",
  srcs=["BusCenter.cpp","Context.cpp","Dropcopy.cpp","Event.cpp","Reader.cpp"],
  hdrs=glob(["*.h"]),
  deps=["//util:util",],
  visibility=["//green:__pkg__",
              "//tetris:__pkg__",
             ],
)